### PR TITLE
Exp2 add tx limits

### PR DESCRIPTION
**Pull request by wa0uwh**

### CODE REVIEW

**Comment by sarfata** [comment]
Thanks @wa0uwh. I see that you have moved all the files in a `radiono` subfolder. Any specific reason for this? (I think I have guessed but I want to be sure ;)

Moving the files seems to have broken the history here so it's impossible to see what has changed in them. This makes reviewing this pull request very difficult. If you really want to move them we should do two pull requests. The first one just to re-organize the files and the second one to actually add your changes. This way we can look at the code differences and make comments.

**Comment by wa0uwh** [comment]
Thomas,

Thanks for the reply. I am assuming you are one of the original radiono
Github owners/users.

I inadvertently press the "Pull Request" button on GitHub, so my request
can be ignored.

But, Yes I moves the files so that a user of the Arduino IDE does not have
to move files or make special arrangements to compile and download the code
into a Controller. And, yes I understand your concern and I am new to
GitHub and do not always use it correctly. Thanks for any help with GitHub.

Of course, my modification are available to anyone interesting in using
them, including you. If you like my mods and find them useful, I will work
as necessary to help make it happen.

See: http://wa0uwh.blogspot.com/2014/08/minima-software-progress.html

I love the idea behind the Minima, thanks to Farhan.

Let me know how you want to proceed.

Regards,
Eldon Brown

73 - Eldon - WA0UWH - CN88xc - http://WA0UWH.blogspot.com/

**Comment by sarfata** [comment]
Farhan gave me access to the repository to help him maintain the project. He is the original author. You have probably seen my name on the minima mailing list (thomas - kk6aht).

I will close this pull request since you say it was done by error but I would like to encourage you to re-submit in smaller pieces that we can discuss so that there is only one Minima source code and not many variations on different websites. Feel free to reach out to me with any git questions. I will be glad to help.

Maybe you could start by submitting a pull request that just moves the files to a radiono subfolder? I agree with you that this has caused more trouble than needed.

**Comment by wa0uwh** [comment]
Thomas,

As you suggested, I checked and my first commit after I forked the radiono
repository was only a directory reorganization.

But I do not know how to construct a "Pull Request" for just that commit. I
tried to re-Fork to do it again, but that did not work. I considered
creating a new GitHub account, but that would seem to defeat the purpose.

How do you suggest I proceed?

Regards,
Eldon Brown

73 - Eldon - WA0UWH - CN88xc - http://WA0UWH.blogspot.com/

**Pull request closed without merging**
